image: python:3.5-alpine

before_script:
  - git clone --recursive https://github.com/getpelican/pelican-plugins /builds/gaulinmp/pelican-plugins

pages:
  script:
  - pip install -r requirements.txt
  - pelican -s publishconf.py
  artifacts:
    paths:
    - output/
