dist: xenial
language: python
python:
    - "3.6"
cache: apt
install:
    - "sudo apt-get install pandoc"
    - "gem install sass"
    - "which sass"
    - "sass --version"
    - "git clone --recursive https://github.com/getpelican/pelican-plugins ../pelican-plugins"
    - "pip install -r requirements.txt"
    - "sass theme/cv/static/css/main.scss test.css"
    - "tail test.css"
script: "make publish"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: ./output
notifications:
    email:
        on_failure: always
