dist: xenial
language: python
python:
  - "3.9"
cache: apt
branches:
  only:
  - master
install:
  - "pip install -r requirements.txt"
script: "make travisci"
after_script:
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - git config credential.helper "store --file=.git/credentials"
  - git clone --quiet --branch=master https://${GITHUB_TOKEN}@github.com/gaulinmp/gaulinmp.github.io ../gaulinmp.github.io
  - rsync -rv --exclude=.git ./output/ ../gaulinmp.github.io
  - cd ../gaulinmp.github.io
  - git add -f .
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to Github Pages"
  - git push origin master
notifications:
  email:
    on_success: always
    on_failure: always
